version: 2.1

orbs:
  ruby: circleci/ruby@1.0 
  node: circleci/node@2

executors:
  default:
    working_directory: ~/repo
    description: The official CircleCI Ruby Docker image
   
    

caches:
  - &bundle_cache v1-repo-{{ checksum "Gemfile.lock" }}

commands:
  run_linters:
    description: command to start linters
    steps:
      - run:
          name: rubocop
          command: bundle exec rubocop

  run_specs:
    steps:
      - run:
          name: run specs
          command: bundle exec rspec 
          when: always
      - store_test_results:
          path: ~/test-results/rspec/
      - store_artifacts:
          path: ~/repo/coverage
          destination: coverage
  setup_environment:
    steps:
      - checkout
      - restore_cache:
          key: *bundle_cache
      - run: bundle install 
      - save_cache:
          key: *bundle_cache
          paths:
            - vendor/bundle
      
      - run:
          name: Set up DB
          command: |
            bundle exec rake db:create
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.2
        environment:
          RAILS_ENV: test
      - image: circleci/postgres:12.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout
      - ruby/install-deps 
      - node/install-packages: 
          pkg-manager: yarn
          cache-key: "yarn.lock"
  lintering:
    executor: default
    steps:
      - setup_environment
      - run_linters
  run_specs:
    executor: default
    steps:
      - setup_environment
      - run_specs

workflows:
  version: 2.1
  build:
    jobs:
      - build
      - lintering
      - run_specs:
          requires:
            - lintering