default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Book_store_development
  
test:
  <<: *default
  username: alex
  password: sasha370
  host: localhost
  port: 5432
  database: bookstore_test

production:
  <<: *default
  database: Book_store_production
  username: Book_store
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
