default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= Rails.application.credentials.dig(:db_login) %>
  password: <%= Rails.application.credentials.dig(:db_password) %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Project_store_development
  host: localhost
  
test:
  <<: *default
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  database: project_store_test

production:
  <<: *default
  database: project_store_production
