default: &default
  adapter: postgresql
  username: <%= ENV['BOOK_STORE_DATABASE_LOGIN'] %>
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Book_store_development
  
test:
  <<: *default
  host: localhost
  port: 5432
  database: bookstore_test

production:
  <<: *default
  database: Book_store_production
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
