default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Book_store_development
  
test:
  <<: *default
  host: localhost
  username: <%= Rails.application.credentials.dig(:test, :BOOK_STORE_DATABASE_LOGIN) %>
  password: <%= Rails.application.credentials.dig(:test, :BOOK_STORE_DATABASE_PASSWORD) %>
  port: 5432
  database: bookstore_test

production:
  <<: *default
  database: Book_store_production
  password: <%= ENV['BOOK_STORE_DATABASE_PASSWORD'] %>
