test:
  service: Disk
  root: <%= Rails.root.join("tmp/storage") %>

local:
  service: Disk
  root: <%= Rails.root.join("storage") %>

# Use rails credentials:edit to set the AWS secrets (as aws:access_key_id|secret_access_key)
amazon:
  service: S3
  access_key_id: <%= Rails.application.credentials.dig(:AWS_ACCESS_KEY_ID) %>
  secret_access_key: <%= Rails.application.credentials.dig(:AWS_SECRET_ACCESS_KEY) %>
  region: us-east-1
  bucket: book-store-sasha370
